spring:
  profiles:
    active:
      - local
  datasource:
    url: "jdbc:h2:tcp://localhost/~/Documents/h2"
    username: "sa"
    driver-class-name: org.h2.Driver


---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true


logging.level:
  org.hibernate.SQL: debug


---
spring:
  config:
    activate:
      on-profile: production
logging.level:
  org.hibernate.SQL: warn