spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}


---
spring:
  config:
    activate:
      on-profile: development

---
spring:
  config:
    activate:
      on-profile: production
